import '../models/department.dart';
import '../models/contact.dart';
import '../models/duty_person.dart';

class MockData {
  // ─── Departments ────────────────────────────────────────────────────────────
  static final List<Department> departments = [
    const Department(
      id: 'd1',
      name: 'Acil Servis',
      category: DepartmentCategory.acilServis,
      isEmergency: true,
    ),
    const Department(
      id: 'd2',
      name: 'Yoğun Bakım Ünitesi',
      category: DepartmentCategory.yogunBakim,
      isEmergency: true,
    ),
    const Department(
      id: 'd3',
      name: 'Ameliyathane',
      category: DepartmentCategory.ameliyathane,
      isEmergency: true,
    ),
    const Department(
      id: 'd4',
      name: 'Dahiliye',
      category: DepartmentCategory.klinik,
    ),
    const Department(
      id: 'd5',
      name: 'Cerrahi Klinik',
      category: DepartmentCategory.klinik,
    ),
    const Department(
      id: 'd6',
      name: 'Kardiyoloji',
      category: DepartmentCategory.klinik,
    ),
    const Department(
      id: 'd7',
      name: 'Nöroloji',
      category: DepartmentCategory.klinik,
    ),
    const Department(
      id: 'd8',
      name: 'Pediatri',
      category: DepartmentCategory.klinik,
    ),
    const Department(
      id: 'd9',
      name: 'Kadın Doğum',
      category: DepartmentCategory.klinik,
    ),
    const Department(
      id: 'd10',
      name: 'Ortopedi',
      category: DepartmentCategory.klinik,
    ),
    const Department(
      id: 'd11',
      name: 'Laboratuvar',
      category: DepartmentCategory.laboratuvar,
    ),
    const Department(
      id: 'd12',
      name: 'Radyoloji',
      category: DepartmentCategory.radyoloji,
    ),
    const Department(
      id: 'd13',
      name: 'Eczane',
      category: DepartmentCategory.diger,
    ),
    const Department(
      id: 'd14',
      name: 'Hasta Kabul',
      category: DepartmentCategory.idari,
    ),
    const Department(
      id: 'd15',
      name: 'Bilgi İşlem',
      category: DepartmentCategory.teknik,
    ),
    const Department(
      id: 'd16',
      name: 'İnsan Kaynakları',
      category: DepartmentCategory.idari,
    ),
    const Department(
      id: 'd17',
      name: 'Güvenlik',
      category: DepartmentCategory.idari,
    ),
    const Department(
      id: 'd18',
      name: 'Teknik Servis',
      category: DepartmentCategory.teknik,
    ),
  ];

  // ─── Contacts ───────────────────────────────────────────────────────────────
  static final List<Contact> contacts = [
    Contact(
      id: 'c1',
      name: 'Dr. Ahmet Yılmaz',
      departmentId: 'd1',
      departmentName: 'Acil Servis',
      internalNumber: '100',
      mobileNumber: '05321234567',
      role: 'Acil Tıp Uzmanı',
    ),
    Contact(
      id: 'c2',
      name: 'Hemş. Fatma Kaya',
      departmentId: 'd1',
      departmentName: 'Acil Servis',
      internalNumber: '101',
      mobileNumber: '05321234568',
      role: 'Hemşire',
    ),
    Contact(
      id: 'c3',
      name: 'Dr. Mehmet Demir',
      departmentId: 'd2',
      departmentName: 'Yoğun Bakım Ünitesi',
      internalNumber: '200',
      mobileNumber: '05331234567',
      role: 'YBÜ Uzmanı',
    ),
    Contact(
      id: 'c4',
      name: 'Hemş. Ayşe Çelik',
      departmentId: 'd2',
      departmentName: 'Yoğun Bakım Ünitesi',
      internalNumber: '201',
      mobileNumber: '05331234568',
      role: 'Hemşire',
    ),
    Contact(
      id: 'c5',
      name: 'Op. Dr. Hasan Şahin',
      departmentId: 'd3',
      departmentName: 'Ameliyathane',
      internalNumber: '300',
      mobileNumber: '05341234567',
      role: 'Genel Cerrah',
    ),
    Contact(
      id: 'c6',
      name: 'Ane. Dr. Zeynep Kurt',
      departmentId: 'd3',
      departmentName: 'Ameliyathane',
      internalNumber: '301',
      mobileNumber: '05341234568',
      role: 'Anesteziyolog',
    ),
    Contact(
      id: 'c7',
      name: 'Dr. Ali Özkan',
      departmentId: 'd4',
      departmentName: 'Dahiliye',
      internalNumber: '400',
      mobileNumber: '05351234567',
      role: 'Dahiliye Uzmanı',
    ),
    Contact(
      id: 'c8',
      name: 'Prof. Dr. Selma Arslan',
      departmentId: 'd6',
      departmentName: 'Kardiyoloji',
      internalNumber: '500',
      mobileNumber: '05361234567',
      role: 'Kardiyoloji Prof.',
    ),
    Contact(
      id: 'c9',
      name: 'Dr. Kemal Aydın',
      departmentId: 'd7',
      departmentName: 'Nöroloji',
      internalNumber: '600',
      mobileNumber: '05371234567',
      role: 'Nöroloji Uzmanı',
    ),
    Contact(
      id: 'c10',
      name: 'Dr. Elif Yıldız',
      departmentId: 'd8',
      departmentName: 'Pediatri',
      internalNumber: '700',
      mobileNumber: '05381234567',
      role: 'Çocuk Hastalıkları',
    ),
    Contact(
      id: 'c11',
      name: 'Dr. Selin Doğan',
      departmentId: 'd9',
      departmentName: 'Kadın Doğum',
      internalNumber: '800',
      mobileNumber: '05391234567',
      role: 'Kadın Doğum Uzmanı',
    ),
    Contact(
      id: 'c12',
      name: 'Lab. Tek. Murat Şen',
      departmentId: 'd11',
      departmentName: 'Laboratuvar',
      internalNumber: '1100',
      mobileNumber: '05301234567',
      role: 'Lab. Teknisyeni',
    ),
    Contact(
      id: 'c13',
      name: 'Rad. Tek. Berna Ak',
      departmentId: 'd12',
      departmentName: 'Radyoloji',
      internalNumber: '1200',
      mobileNumber: '05301234568',
      role: 'Radyoloji Tek.',
    ),
    Contact(
      id: 'c14',
      name: 'Ecz. Tolga Can',
      departmentId: 'd13',
      departmentName: 'Eczane',
      internalNumber: '1300',
      mobileNumber: '05301234569',
      role: 'Eczacı',
    ),
    Contact(
      id: 'c15',
      name: 'Hasta Kabul Merkezi',
      departmentId: 'd14',
      departmentName: 'Hasta Kabul',
      internalNumber: '0',
      role: 'Santral',
    ),
    Contact(
      id: 'c16',
      name: 'BT Sorumlusu Emre Bulut',
      departmentId: 'd15',
      departmentName: 'Bilgi İşlem',
      internalNumber: '1500',
      mobileNumber: '05321239999',
      role: 'BT Uzmanı',
    ),
    Contact(
      id: 'c17',
      name: 'Güvenlik Amiri',
      departmentId: 'd17',
      departmentName: 'Güvenlik',
      internalNumber: '1700',
      mobileNumber: '05321238888',
      role: 'Güvenlik',
    ),
    Contact(
      id: 'c18',
      name: 'Teknik Servis',
      departmentId: 'd18',
      departmentName: 'Teknik Servis',
      internalNumber: '1800',
      role: 'Teknik',
    ),
    Contact(
      id: 'c19',
      name: 'İK Birimi',
      departmentId: 'd16',
      departmentName: 'İnsan Kaynakları',
      internalNumber: '1600',
      role: 'İK',
    ),
    Contact(
      id: 'c20',
      name: 'Op. Dr. Caner Erdoğan',
      departmentId: 'd5',
      departmentName: 'Cerrahi Klinik',
      internalNumber: '450',
      mobileNumber: '05351234570',
      role: 'Genel Cerrah',
    ),
  ];

  // ─── Emergency Contacts (top 5) ─────────────────────────────────────────────
  static List<Contact> get emergencyContacts {
    return contacts
        .where((c) => ['c1', 'c3', 'c5', 'c8', 'c15'].contains(c.id))
        .toList();
  }

  // ─── Duty Personnel ─────────────────────────────────────────────────────────
  static List<DutyPerson> generateDutyList() {
    final now = DateTime.now();
    final List<DutyPerson> duties = [];

    // Helper to add days
    DateTime day(int offset) => DateTime(now.year, now.month, now.day + offset);

    final dutyData = [
      // Today
      [
        'dp1',
        'Dr. Ahmet Yılmaz',
        'd1',
        'Acil Servis',
        PersonnelRole.doktor,
        '05321234567',
        0,
        true,
      ],
      [
        'dp2',
        'Hemş. Fatma Kaya',
        'd1',
        'Acil Servis',
        PersonnelRole.hemsire,
        '05321234568',
        0,
        true,
      ],
      [
        'dp3',
        'Dr. Mehmet Demir',
        'd2',
        'Yoğun Bakım',
        PersonnelRole.doktor,
        '05331234567',
        0,
        true,
      ],
      [
        'dp4',
        'Hemş. Ayşe Çelik',
        'd2',
        'Yoğun Bakım',
        PersonnelRole.hemsire,
        '05331234568',
        0,
        true,
      ],
      [
        'dp5',
        'Op. Dr. Hasan Şahin',
        'd3',
        'Ameliyathane',
        PersonnelRole.doktor,
        '05341234567',
        0,
        true,
      ],
      [
        'dp6',
        'Dr. Ali Özkan',
        'd4',
        'Dahiliye',
        PersonnelRole.doktor,
        '05351234567',
        0,
        false,
      ],
      [
        'dp7',
        'Hemş. Selin Demir',
        'd6',
        'Kardiyoloji',
        PersonnelRole.hemsire,
        '05361234570',
        0,
        false,
      ],
      [
        'dp8',
        'Dr. Zeynep Kurt',
        'd3',
        'Ameliyathane',
        PersonnelRole.doktor,
        '05341234568',
        0,
        true,
      ],
      // Tomorrow
      [
        'dp9',
        'Dr. Kemal Aydın',
        'd7',
        'Nöroloji',
        PersonnelRole.doktor,
        '05371234567',
        1,
        false,
      ],
      [
        'dp10',
        'Hemş. Merve Yıldız',
        'd1',
        'Acil Servis',
        PersonnelRole.hemsire,
        '05321234570',
        1,
        true,
      ],
      [
        'dp11',
        'Dr. Elif Yıldız',
        'd8',
        'Pediatri',
        PersonnelRole.doktor,
        '05381234567',
        1,
        false,
      ],
      [
        'dp12',
        'Dr. Selin Doğan',
        'd9',
        'Kadın Doğum',
        PersonnelRole.doktor,
        '05391234567',
        1,
        false,
      ],
      // Day +2
      [
        'dp13',
        'Dr. Caner Erdoğan',
        'd5',
        'Cerrahi',
        PersonnelRole.doktor,
        '05351234570',
        2,
        false,
      ],
      [
        'dp14',
        'Hemş. Burak Çetin',
        'd2',
        'Yoğun Bakım',
        PersonnelRole.hemsire,
        '05331234570',
        2,
        true,
      ],
      [
        'dp15',
        'Dr. Tolga Kara',
        'd4',
        'Dahiliye',
        PersonnelRole.doktor,
        '05352234567',
        2,
        false,
      ],
      // Day +3
      [
        'dp16',
        'Dr. Ece Arslan',
        'd6',
        'Kardiyoloji',
        PersonnelRole.doktor,
        '05361234567',
        3,
        false,
      ],
      [
        'dp17',
        'Hemş. Gizem Ay',
        'd1',
        'Acil Servis',
        PersonnelRole.hemsire,
        '05321234572',
        3,
        true,
      ],
      [
        'dp18',
        'Dr. Barış Yurt',
        'd3',
        'Ameliyathane',
        PersonnelRole.doktor,
        '05341234570',
        3,
        true,
      ],
      // Day +4
      [
        'dp19',
        'Dr. Nur Kaya',
        'd7',
        'Nöroloji',
        PersonnelRole.doktor,
        '05371234568',
        4,
        false,
      ],
      [
        'dp20',
        'Hemş. Sercan Bal',
        'd2',
        'Yoğun Bakım',
        PersonnelRole.hemsire,
        '05331234572',
        4,
        true,
      ],
      // Day +5
      [
        'dp21',
        'Dr. Mert Şen',
        'd8',
        'Pediatri',
        PersonnelRole.doktor,
        '05381234568',
        5,
        false,
      ],
      [
        'dp22',
        'Hemş. Deniz Öz',
        'd9',
        'Kadın Doğum',
        PersonnelRole.hemsire,
        '05391234568',
        5,
        false,
      ],
      // Day +6
      [
        'dp23',
        'Dr. Pelin Ak',
        'd1',
        'Acil Servis',
        PersonnelRole.doktor,
        '05321234575',
        6,
        true,
      ],
      [
        'dp24',
        'Hemş. Onur Tan',
        'd3',
        'Ameliyathane',
        PersonnelRole.hemsire,
        '05341234575',
        6,
        true,
      ],
    ];

    for (final d in dutyData) {
      duties.add(
        DutyPerson(
          id: d[0] as String,
          name: d[1] as String,
          departmentId: d[2] as String,
          departmentName: d[3] as String,
          role: d[4] as PersonnelRole,
          phone: d[5] as String,
          dutyDate: day(d[6] as int),
          dutyStartTime: '08:00',
          dutyEndTime: '08:00 (+1)',
          isCriticalUnit: d[7] as bool,
        ),
      );
    }

    return duties;
  }
}
